---
language: python
python: "2.7.15"
sudo: required

services:
  - docker

install:
  - pip install pipenv
  - pipenv install -r test-requirements.txt --python 2.7
env:
  global:
    - PACKAGE=auditbeat
  matrix:
    # RHEL 8
    - DOCKER_IMAGE_BASE=apolloclark/ubi8:8
      DOCKER_INST_NAME_SUFFIX=rhel_8
      PACKAGE_VERSION=7.3.0

    # RHEL 7
    - DOCKER_IMAGE_BASE=apolloclark/ubi7:7
      DOCKER_INST_NAME_SUFFIX=rhel_7
      PACKAGE_VERSION=7.3.0

    # CentOS 7
    - DOCKER_IMAGE_BASE=centos:7
      DOCKER_INST_NAME_SUFFIX=centos_7
      PACKAGE_VERSION=7.3.0

    # Amazon Linux 2
    - DOCKER_IMAGE_BASE=amazonlinux:2
      DOCKER_INST_NAME_SUFFIX=amzlinux_2
      PACKAGE_VERSION=7.3.0

    # Ubuntu 18.04 Bionic
    - DOCKER_IMAGE_BASE=ubuntu:18.04
      DOCKER_INST_NAME_SUFFIX=ubuntu_18.04
      PACKAGE_VERSION=7.3.0

    # Ubuntu 16.04 Xenial
    - DOCKER_IMAGE_BASE=ubuntu:xenial
      DOCKER_INST_NAME_SUFFIX=ubuntu_16.04
      PACKAGE_VERSION=7.3.0

    # Debian 10 Buster
    - DOCKER_IMAGE_BASE=debian:10
      DOCKER_INST_NAME_SUFFIX=debian_10
      PACKAGE_VERSION=7.3.0

    # Debian 9 Stretch
    - DOCKER_IMAGE_BASE=debian:9
      DOCKER_INST_NAME_SUFFIX=debian_9
      PACKAGE_VERSION=7.3.0



    # RHEL 8
    - DOCKER_IMAGE_BASE=apolloclark/ubi8:8
      DOCKER_INST_NAME_SUFFIX=rhel_8
      PACKAGE_VERSION=6.8.2

    # RHEL 7
    - DOCKER_IMAGE_BASE=apolloclark/ubi7:7
      DOCKER_INST_NAME_SUFFIX=rhel_7
      PACKAGE_VERSION=6.8.2

    # CentOS 7
    - DOCKER_IMAGE_BASE=centos:7
      DOCKER_INST_NAME_SUFFIX=centos_7
      PACKAGE_VERSION=6.8.2

    # Amazon Linux 2
    - DOCKER_IMAGE_BASE=amazonlinux:2
      DOCKER_INST_NAME_SUFFIX=amzlinux_2
      PACKAGE_VERSION=6.8.2

    # Ubuntu 18.04 Bionic
    - DOCKER_IMAGE_BASE=ubuntu:18.04
      DOCKER_INST_NAME_SUFFIX=ubuntu_18.04
      PACKAGE_VERSION=6.8.2

    # Ubuntu 16.04 Xenial
    - DOCKER_IMAGE_BASE=ubuntu:16.04
      DOCKER_INST_NAME_SUFFIX=ubuntu_16.04
      PACKAGE_VERSION=6.8.2

    # Debian 10 Buster
    - DOCKER_IMAGE_BASE=debian:10
      DOCKER_INST_NAME_SUFFIX=debian_10
      PACKAGE_VERSION=6.8.2

    # Debian 9 Stretch
    - DOCKER_IMAGE_BASE=debian:9
      DOCKER_INST_NAME_SUFFIX=debian_9
      PACKAGE_VERSION=6.8.2

script:
  - pipenv run molecule test --all
