---
- name: Add Elastic 6.x repo (if choosing a 6.x version)
  yum_repository:
    name: metricbeat
    description: Beats Repo
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpgkey: https://packages.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: yes
    enabled: yes
    owner: root
    group: root
    state: present
    mode: 0600
  when:
    - auditbeat_combined.version is version_compare('6', '>=')
    - auditbeat_combined.version is version_compare('7', '<')
    - auditbeat_combined.install_repo

- name: Install from repo (if choosing the 5.6.x or 6.x version)
  yum:
    name: "auditbeat-{{ auditbeat_combined.version }}"
    state: present
  when:
    - auditbeat_combined.version is version_compare('6', '>=')
    - auditbeat_combined.version is version_compare('7', '<')
    - auditbeat_combined.install_repo

