---

# https://www.elastic.co/guide/en/beats/auditbeat/master/setup-repositories.html#_yum
# https://docs.ansible.com/ansible/latest/modules/rpm_key_module.html
- name: RedHat, Add repository key
  rpm_key:
    key: "https://packages.elastic.co/GPG-KEY-elasticsearch"
    state: present
  when:
    - auditbeat_combined.install_repo

# http://docs.ansible.com/ansible/latest/yum_repository_module.html
- name: RedHat, Add Elastic 7.x repo (if choosing a 7.x version)
  yum_repository:
    name: 'elastic-7.x'
    description: 'Elastic repository for 7.x packages'
    baseurl: 'https://artifacts.elastic.co/packages/7.x/yum'
    gpgcheck: 1
    gpgkey: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'
    enabled: 1
    state: present
  when:
    - auditbeat_combined.version is version('7', '>=')
    - auditbeat_combined.version is version('8', '<')
    - auditbeat_combined.install_repo

# http://docs.ansible.com/ansible/latest/yum_repository_module.html
- name: RedHat, Add Elastic 6.x repo (if choosing a 6.x version)
  yum_repository:
    name: 'elastic-6.x'
    description: 'Elastic repository for 6.x packages'
    baseurl: 'https://artifacts.elastic.co/packages/6.x/yum'
    gpgcheck: 1
    gpgkey: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'
    enabled: 1
    state: present
  when:
    - auditbeat_combined.version is version('6', '>=')
    - auditbeat_combined.version is version('7', '<')
    - auditbeat_combined.install_repo

# https://docs.ansible.com/ansible/latest/modules/yum_module.html
- name: RedHat, Install from repo (if choosing the 5.6.x, 6.x, or 7.x version)
  yum:
    name: "auditbeat-{{ auditbeat_combined.version }}-1"
    update_cache: true
    state: present
  until: package_installed is succeeded
  register: package_installed
  when:
    - auditbeat_combined.version is version('6', '>=')
    - auditbeat_combined.version is version('8', '<')
    - auditbeat_combined.install_repo
