---
- name: Get the simplified major.minor version string
  set_fact:
    version_simple: "{{ auditbeat.version | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2') }}"

- name: Include defaults for configuration, per the requested version.
  include_vars:
    file: main-{{ version_simple }}.yml

- name: Merge auditbeat_default and auditbeat variables
  set_fact:
    auditbeat_combined: "{{ auditbeat_defaults | combine(auditbeat, recursive=True) }}"

- include: install-{{ansible_os_family}}.yml

- name: Ensure auditbeat auto-starts
  service:
    name: auditbeat
    enabled: yes

- name: Copy config file
  template:
    src: "auditbeat-{{ version_simple }}.yml"
    dest: "{{ auditbeat_combined.config_include_dir }}/auditbeat.yml"
    owner: root
    group: root
    mode: 0644
  when:
    - not auditbeat_combined.install_only

- name: Restart auditbeat
  service:
    name: "{{ auditbeat_combined.daemon }}"
    state: restarted
  when:
    - not auditbeat_combined.install_only

- name: Ensure that the service is running
  service: 
    name: auditbeat
    state: started
    enabled: yes
  when:
    - not auditbeat_combined.install_only
