---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: ${DOCKER_IMAGE_BASE:-ubuntu:bionic}
    groups:
      - auditbeat
provisioner:
  name: ansible
  inventory:
    group_vars:
      auditbeat:
        auditbeat:
          version: "6.6.2"
          skip_restart: true
  lint:
    name: ansible-lint
verifier:
  name: goss
  lint:
    name: yamllint
